Repository Prithwi32/ChatHub, pull requests merged in 2025-03, with the labels that each got.

#37 contact us page in navbar
  client/src/components/Navbar.jsx
Labels: bug, jwoc2k25, easy, jwoc

#42 Enhanced the chatroom join page interface
  client/src/assets/images/chat.png
  client/src/components/ChatRoom.jsx
Labels: jwoc2k25, medium, jwoc

#44 Fixed chat interface
  client/package-lock.json
  client/package.json
  client/src/components/ChatRoom.jsx
Labels: enhancement, question, jwoc2k25, hard, jwoc

#39 authentication done with backend
  client/package.json
  client/src/App.jsx
  client/src/components/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/Signup.jsx
  server/package-lock.json
  server/package.json
  server/routes/userRoutes.js
Labels: enhancement, jwoc2k25, hard, jwoc, inreview
