Repository Prithwi32/ChatHub, pull requests merged in 2025-02, with the labels that each got.

#9 Create Landing Page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/AboutUs.jsx
  client/src/components/ChatRoom.jsx
  client/src/components/ChooseUs.jsx
  client/src/components/Cta.jsx
  client/src/components/Features.jsx
  client/src/components/Footer.jsx
  client/src/components/LandingPage.jsx
  client/src/components/Navbar.jsx
  client/src/images/About-Us.png
  client/src/images/Encryption.png
  client/src/images/Fast-Performance.png
  client/src/images/Group-Chat.png
  client/src/images/Group.png
  client/src/images/Messaging.png
  client/src/images/Multi-Device.png
  client/src/images/Privacy.png
  client/src/images/free.png
  client/src/images/simple.png
  client/src/main.jsx
Labels: enhancement, good first issue, jwoc2k25, medium, jwoc

#14 added dark mode feature
  client/src/components/AboutUs.jsx
  client/src/components/ChatRoom.jsx
  client/src/components/ChooseUs.jsx
  client/src/components/Contact.jsx
  client/src/components/Cta.jsx
  client/src/components/Features.jsx
  client/src/components/Footer.jsx
  client/src/components/LandingPage.jsx
  client/src/components/Navbar.jsx
  client/src/context/ThemeContext.jsx
  client/src/index.css
  client/src/main.jsx
  client/tailwind.config.js
Labels: enhancement, help wanted, jwoc2k25, medium, jwoc

#18 feat: Implemented User Profile with options to customize user preferences
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/images/profile.jpg
  client/src/pages/UserProfile.jsx
Labels: enhancement, jwoc2k25, hard, jwoc

#16 🚀 UI Enhancements & Dark Mode Improvements for Navbar and Landing Page
  client/index.html
  client/src/components/ChatRoom.jsx
  client/src/components/Cta.jsx
  client/src/components/LandingPage.jsx
  client/src/components/Navbar.jsx
Labels: question, jwoc2k25, jwoc

#27 Applied transition
  client/src/components/Footer.jsx
Labels: bug, good first issue, jwoc2k25, easy, jwoc

#26 Modify Scrollbar
  client/src/App.jsx
  client/src/index.css
Labels: good first issue, jwoc2k25, easy, jwoc

#30 Responsiveness: Ui Changes
  client/package-lock.json
  client/package.json
  client/src/components/AboutUs.jsx
  client/src/components/ChooseUs.jsx
  client/src/components/Features.jsx
  client/src/components/Navbar.jsx
Labels: good first issue, jwoc2k25, hard, jwoc

#31 Update README.md
  README.md
Labels: bug, documentation, jwoc2k25, medium, jwoc
